### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by andre15silva** [SpoonLabs/flacoco#14]
- [x] Re-enable CI for test execution (#16)
- [x] Enable code coverage (#16)
- [x] Enable deployment in CI (#27)
- [x] Several JVM versions in CI (#27) Closes #5
- [x] Move to GitHub Actions (#27) Closes #5

**Comment by andre15silva** [comment]
I'm not very knowledgeable about the CI options.

WDYT, should we stick with Travis or move to GitHub Actions?

**Comment by martinezmatias** [comment]
Hi @andre15silva 

About Travis: @monperrus  has recently obtained credits for the SpoonLabs organization. Consequently, we could execute CI on Travis-ci.com.

For me it's fine to move to Github Actions. However, I have never try it before.

Regards
Matias

**Comment by martinezmatias** [comment]
Hi André
Ticket on sonatype asking for your rights: https://issues.sonatype.org/browse/OSSRH-49772?focusedCommentId=1068892&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1068892

**Comment by martinezmatias** [comment]
Hi André:
Permissions granted: 
https://issues.sonatype.org/browse/OSSRH-49772?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=1069447#comment-1069447
